### ISSUE TITLE
Using SDK with LINQ and property names 

### ISSUE THREAD

**Issue by nhwilly** [ealsur/ondotnet-cosmosdb#2]
What a great addition.  This is what allowed me to use `System.Text.Json` in my projects.  Thank you.

I did notice that I have to use normal casing (not Camel Case) for my property names to work with LINQ queries.

That's not ideal, but I suspect it's because the internals of Cosmos are still Newtonsoft dependent.

Anyway, thanks for this.

**Comment by ealsur** [comment]
The code in this repo/example is not updated, maybe https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/CosmosSystemTextJsonSerializer.cs might be better

**Comment by nhwilly** [comment]
Thanks for the quick response. I'll give it a shot.
