### ISSUE TITLE
Is StreamApi really faking it?

### ISSUE THREAD

**Issue by ali-asghar5** [ealsur/ondotnet-cosmosdb#3]
Hi mate,
Thanks for the sample/ demo and tutorial. 

If I use Is Stream APIs, it resulted as completed successfully but no data appear at database. If I switch it with CreateItemAsync then it works but I get Exception 429.

Have I missed anything...

Cheers

**Comment by ealsur** [comment]
@ali-asghar5 

> as completed successfully

Are you checking the ResponseMessage StatusCode? Or the ResponseMessage.IsSuccessStatusCode?

A 429 with the Stream APIs will still return a ResponseMessage (there are no exceptions, that's the whole point). You need to inspect the result.

**Comment by ali-asghar5** [comment]
![image](https://github.com/user-attachments/assets/7adabe62-9a79-44e8-a20c-2f7400c3e294)

Above is what I get

**Comment by ealsur** [comment]
Right, that is not a success. The StatusCode is HTTP 400 (Bad Request). The Stream API is working as expected.

![image](https://github.com/user-attachments/assets/c0021d40-fd81-4cbb-a774-f1f5035fa935)

Stream APIs won't throw exceptions, it will return the raw response, your code should check if the response is a success or not if you have logic that depends on it.

Just like when you use the Typed-APIs, you try/catch and handle exceptions if that layer needs to.

**Comment by ali-asghar5** [comment]
Ah got it. How can I investigate BadRequest, response doesn't carry any message. I can successfully create items using CreateItemAsync just not with CreateItemStreamAsync using the same partition key.

**Comment by ali-asghar5** [comment]
Found the issue, I setting CosmosPropertyNamingPolicy.CamelCase for cosmos client SerializerOptions.

https://stackoverflow.com/questions/63799147/how-to-bulk-insert-in-cosmos-db-with-net-core-2-1-and-stream-api
